import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, CalendarDays, CheckCircle2, Clock3, MessageSquareText, RefreshCw, Users } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuth } from "../auth/AuthContext";
import { api } from "../services/api";

type Stats={totalTrainings:number;completedTrainings:number;totalEmployees:number;attendancePercentage:number;feedbackCount:number;pendingFeedback:number;pendingEvaluations:number;evaluationFeedback:number;trainingTypes:{type:string;count:number}[]};
type Progress={trainingId:string;trainingTitle:string;employeeId:string;employeeName:string;department:string;attendance:string;completionStatus:string;feedbackStatus:string};
const empty:Stats={totalTrainings:0,completedTrainings:0,totalEmployees:0,attendancePercentage:0,feedbackCount:0,pendingFeedback:0,pendingEvaluations:0,evaluationFeedback:0,trainingTypes:[]};
export default function Dashboard(){
 const {user}=useAuth(); const [s,setS]=useState(empty); const [progress,setProgress]=useState<Progress[]>([]); const [startDate,setStartDate]=useState(""); const [endDate,setEndDate]=useState(""); const [refreshing,setRefreshing]=useState(false);
 const load=async()=>{setRefreshing(true);try{const q=new URLSearchParams();if(startDate)q.set('startDate',startDate);if(endDate)q.set('endDate',endDate);const [a,p]=await Promise.all([api.get<Stats>(`/dashboard${q.toString()?`?${q}`:''}`),api.get<Progress[]>('/trainings/progress')]);setS({...empty,...a.data});setProgress(p.data||[])}finally{setRefreshing(false)}};
 useEffect(()=>{load().catch(()=>{})},[startDate,endDate]);
 const kpis=user?.role==='HR_ADMIN'?[['Total Trainings',s.totalTrainings],['Active Employees',s.totalEmployees],['Completed',s.completedTrainings],['Attendance',`${s.attendancePercentage}%`],['Feedback',s.feedbackCount],['Evaluation Feedback',s.evaluationFeedback]]:user?.role==='MANAGER'?[['Team Trainings',s.totalTrainings],['Team Members',s.totalEmployees],['Completed',s.completedTrainings],['Attendance',`${s.attendancePercentage}%`],['Feedback',s.feedbackCount],['Evaluation Feedback',s.evaluationFeedback]]:[['Assigned Trainings',s.totalTrainings],['Completed',s.completedTrainings],['Attendance',`${s.attendancePercentage}%`],['Feedback Due',s.pendingFeedback]];
 const statusClass=(x:string)=>x==='Completed'?'bg-emerald-50 text-emerald-700':x==='In Progress'?'bg-indigo-50 text-indigo-700':'bg-amber-50 text-amber-700';
 return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-indigo-600">{user?.role.replace('_',' / ')}</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Training Dashboard</h1><p className="mt-2 text-sm text-slate-500">Track training, attendance, feedback and effectiveness.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-sm"/><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="rounded-xl border bg-white px-3 py-2 text-sm"/><button onClick={()=>load().catch(()=>{})} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-semibold"><RefreshCw size={15} className={refreshing?'animate-spin':''}/> Refresh</button></div></div>
 <div className={`grid grid-cols-2 gap-4 ${kpis.length>4?'lg:grid-cols-3 xl:grid-cols-6':'lg:grid-cols-4'}`}>{kpis.map(([a,b])=><div key={String(a)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-wide text-slate-500">{a}</p><p className="mt-3 text-2xl font-bold">{b}</p></div>)}</div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-indigo-50 p-3 text-indigo-600"><BarChart3 size={20}/></div><div><h2 className="font-semibold">Training type distribution</h2><p className="text-sm text-slate-500">Technical, Behavioural and Leadership</p></div></div><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={s.trainingTypes}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="type"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" name="Trainings"/></BarChart></ResponsiveContainer></div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Action required</h2><div className="mt-5 space-y-3">{[{Icon:MessageSquareText,label:'Pending feedback',value:s.pendingFeedback},{Icon:Clock3,label:'Pending evaluations',value:s.pendingEvaluations},{Icon:CheckCircle2,label:'Evaluation feedback',value:s.evaluationFeedback}].map(({Icon,label,value})=><div key={label} className="flex items-center gap-4 rounded-xl bg-slate-50 p-4"><div className="rounded-xl bg-white p-3 text-indigo-600 shadow-sm"><Icon size={19}/></div><div className="flex-1"><p className="text-sm font-semibold">{label}</p><p className="text-xs text-slate-500">{value} record(s)</p></div><ArrowRight size={17} className="text-slate-400"/></div>)}</div></section></div>
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Training progress</h2><p className="text-sm text-slate-500">Live assignments and completion status.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">Live</span></div>{progress.length===0?<div className="mt-5 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">No training assignments found.</div>:<div className="mt-5 space-y-3">{progress.slice(0,30).map((p,i)=><div key={`${p.trainingId}-${p.employeeId}-${i}`} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-semibold">{p.trainingTitle}</p><p className="mt-1 text-xs text-slate-500">{p.employeeName} ({p.employeeId}) · {p.department}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${statusClass(p.completionStatus)}`}>{p.completionStatus}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-3"><span className="rounded-lg bg-slate-50 px-3 py-2">Attendance: <b>{p.attendance}</b></span><span className="rounded-lg bg-slate-50 px-3 py-2">Feedback: <b>{p.feedbackStatus}</b></span><span className="rounded-lg bg-slate-50 px-3 py-2">Employee: <b>{p.employeeId}</b></span></div></div>)}</div>}</section></div>;
}
