import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Plus, Search } from "lucide-react";
import { api } from "../services/api";

type Employee = { _id?: string; employeeId: string; name: string; department: string; designation: string; reportingManager?: string; email?: string; status: string };
type Department = { _id: string; name: string; status: string };

const empty = { employeeId:"", name:"", department:"Production", designation:"", reportingManager:"", email:"", status:"Active", password:"" };

export default function Employees() {
  const [rows, setRows] = useState<Employee[]>([]); const [departments, setDepartments] = useState<Department[]>([]);
  const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState(empty);
  const load = async()=>{ try { const [e,d]=await Promise.all([api.get("/employees"),api.get("/departments")]); setRows(e.data); setDepartments(d.data); } catch(err:any){ setError(err?.response?.data?.message||"Unable to load employees."); } };
  useEffect(()=>{load();},[]);
  const filtered = useMemo(()=>rows.filter(r=>`${r.employeeId} ${r.name} ${r.department} ${r.designation}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
  const add = async(e:FormEvent)=>{ e.preventDefault(); setSaving(true); setError(""); try { await api.post("/employees",form); setOpen(false); setForm(empty); await load(); } catch(err:any){ setError(err?.response?.data?.message||"Unable to create employee."); } finally { setSaving(false); } };
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-indigo-600">HR / Admin</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Employee Management</h1><p className="mt-2 text-sm text-slate-500">Maintain employee, department and reporting-manager information.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/> Add Employee</button></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="relative"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by employee ID, name, department..." className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-indigo-500"/></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50"><tr>{["Employee ID","Name","Department","Designation","Reporting Manager","Status"].map(x=><th key={x} className="p-4 text-left font-semibold text-slate-600">{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r._id||r.employeeId} className="border-t border-slate-100"><td className="p-4 font-semibold">{r.employeeId}</td><td className="p-4">{r.name}</td><td className="p-4">{r.department}</td><td className="p-4">{r.designation}</td><td className="p-4">{r.reportingManager||"—"}</td><td className="p-4"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{r.status}</span></td></tr>)}</tbody></table></div></div>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={add} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Add Employee & Login</h2><p className="mt-1 text-sm text-slate-500">HR creates the Employee ID and initial password. The employee can change the password later.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{([["Employee ID","employeeId"],["Name","name"],["Designation","designation"],["Reporting Manager","reportingManager"],["Email","email"],["Initial Password","password"]] as const).map(([label,key])=><div key={key}><label className="mb-1.5 block text-sm font-medium">{label}</label><input required={!["reportingManager","email"].includes(key)} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div>)}<div><label className="mb-1.5 block text-sm font-medium">Department</label><select value={form.department} onChange={e=>setForm({...form,department:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{departments.filter(d=>d.status!=="Inactive").map(d=><option key={d._id}>{d.name}</option>)}</select></div></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{saving?"Saving...":"Save Employee"}</button></div></form></div>}
  </div>;
}
