import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CheckCircle2, Send } from "lucide-react";
import { api } from "../services/api";
import { useAuth } from "../auth/AuthContext";

const ratingRows = ["Programme Design", "Presentation of Information", "Amount of Information", "Administrative arrangements", "overall"];
const ratingLabels = ["Poor", "Fair", "Good", "V Good", "Excellent"];
const knowledge = ["Totally known to me", "Mostly known to me", "Somewhat known to me", "Little known to me", "Almost nothing known to me"];
const mapRating = (x: string) => ({ Poor: 1, Fair: 2, Good: 3, "V Good": 4, Excellent: 5 } as Record<string, number>)[x] || 0;

type Training = { _id: string; title: string; trainerName?: string; venue?: string; trainingDate?: string };

export default function Feedback() {
  const { user } = useAuth();
  const [trainings, setTrainings] = useState<Training[]>([]); const [trainingId,setTrainingId]=useState("");
  const [ratings,setRatings]=useState<Record<string,string>>({}); const [knowledgeLevel,setKnowledgeLevel]=useState<Record<string,string>>({});
  const [text,setText]=useState({bestModule:"",missedModule:"",majorLearning:"",ideasToImplement:"",remarks:""}); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{api.get<Training[]>("/trainings").then(r=>{setTrainings(r.data); if(r.data[0]) setTrainingId(r.data[0]._id)}).catch(()=>{});},[]);
  const selected=useMemo(()=>trainings.find(t=>t._id===trainingId),[trainings,trainingId]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(!trainingId){setError("Please select a training.");return;}if(ratingRows.some(x=>!ratings[x])){setError("Please complete all course ratings.");return;}try{await api.post("/feedback",{trainingId,employeeId:user?.employeeId,programme:selected?.title,participantName:user?.name,designation:"",location:selected?.venue||"",dates:selected?.trainingDate||"",trainer:selected?.trainerName||"",ratings:Object.fromEntries(Object.entries(ratings).map(([k,v])=>[k,mapRating(v)])),knowledgeBefore:knowledgeLevel["before"]||"",knowledgeAfter:knowledgeLevel["after"]||"",...text});setMessage("Thank you. Your feedback has been submitted.");}catch(err:any){setError(err?.response?.data?.message||"Unable to submit feedback.");}};
  return <div className="mx-auto max-w-5xl space-y-6"><div><p className="text-sm font-medium text-indigo-600">Employee Feedback</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Training Feedback Form</h1><p className="mt-2 text-sm text-slate-500">Digital version based on the supplied company form.</p></div>
    {message&&<div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700"><CheckCircle2 size={18}/>{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
    <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-4 border-b border-slate-100 p-5 sm:p-7"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl border-2 border-dashed border-slate-300 text-[10px] font-bold text-slate-400">LOGO</div><div><h2 className="text-lg font-bold tracking-wide">TRAINING FEEDBACK FORM</h2><p className="text-xs text-slate-500">Logo placeholder — replace later with the company logo.</p></div></div>
    <form onSubmit={submit} className="space-y-8 p-5 sm:p-7"><section className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><label className="mb-2 block text-sm font-medium">Programme</label><select value={trainingId} onChange={e=>setTrainingId(e.target.value)} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select assigned training</option>{trainings.map(t=><option key={t._id} value={t._id}>{t.title}</option>)}</select></div>{[["Participant's Name",user?.name||""],["Designation","Employee designation"],["Location",selected?.venue||""],["Date(s)",selected?.trainingDate||""],["Trainer",selected?.trainerName||""]].map(([label,val])=><div key={label}><label className="mb-2 block text-sm font-medium text-slate-700">{label}</label><input value={val} readOnly className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"/></div>)}</section>
    <section><h3 className="mb-3 text-base font-semibold">Please rate the following aspects of the course</h3><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[760px] w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Aspect</th>{ratingLabels.map(x=><th key={x} className="p-3 text-center">{x}</th>)}</tr></thead><tbody>{ratingRows.map(row=><tr key={row} className="border-t border-slate-100"><td className="p-3 font-medium">{row==="overall"?"OVERALL RATING":row}</td>{ratingLabels.map(x=><td key={x} className="p-3 text-center"><input type="radio" name={`rating-${row}`} checked={ratings[row]===x} onChange={()=>setRatings({...ratings,[row]:x})} className="h-4 w-4 accent-indigo-600"/></td>)}</tr>)}</tbody></table></div></section>
    <section><h3 className="mb-3 text-base font-semibold">Knowledge before / after programme</h3><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[760px] w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Knowledge level</th>{knowledge.map(x=><th key={x} className="p-3 text-center">{x}</th>)}</tr></thead><tbody>{[["before","Knowledge before programme"],["after","Knowledge after programme"]].map(([key,label])=><tr key={key} className="border-t border-slate-100"><td className="p-3 font-medium">{label}</td>{knowledge.map(x=><td key={x} className="p-3 text-center"><input type="radio" name={key} checked={knowledgeLevel[key]===x} onChange={()=>setKnowledgeLevel({...knowledgeLevel,[key]:x})} className="h-4 w-4 accent-indigo-600"/></td>)}</tr>)}</tbody></table></div></section>
    <section className="grid gap-5">{[["Which module you liked best","bestModule"],["Which module you think we missed","missedModule"],["What was the major learning for you","majorLearning"],["Ideas you can implement","ideasToImplement"],["Any other Remarks","remarks"]].map(([label,key])=><div key={key}><label className="mb-2 block text-sm font-medium">{label}</label><textarea rows={key==="remarks"?4:3} value={text[key as keyof typeof text]} onChange={e=>setText({...text,[key]:e.target.value})} className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500"/></div>)}</section>
    <div className="flex justify-end border-t border-slate-100 pt-6"><button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white"><Send size={17}/> Submit Feedback</button></div></form></div></div>;
}
