import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CheckCircle2, Edit3, Send } from "lucide-react";
import { api } from "../services/api";
import { useAuth } from "../auth/AuthContext";

const ratingRows=["Programme Design","Presentation of Information","Amount of Information","Administrative arrangements","overall"];
const labels=["Poor","Fair","Good","V Good","Excellent"];
const knowledge=["Totally known to me","Mostly known to me","Somewhat known to me","Little known to me","Almost nothing known to me"];
const score=(x:string)=>({Poor:1,Fair:2,Good:3,"V Good":4,Excellent:5}[x]||0);
type Training={_id:string;title:string;trainerName?:string;venue?:string;startDate?:string;trainingDate?:string};
type Employee={employeeId:string;name?:string;department?:string};
type FeedbackRow={trainingId:string;employeeId:string;employeeName?:string;department?:string;trainingTitle?:string;ratings:Record<string,number>;status?:string};
export default function Feedback(){
 const {user}=useAuth();const employee=user?.role==="EMPLOYEE";const [trainings,setTrainings]=useState<Training[]>([]);const [employees,setEmployees]=useState<Employee[]>([]);const [rows,setRows]=useState<FeedbackRow[]>([]);const [trainingId,setTrainingId]=useState("");const [employeeId,setEmployeeId]=useState(user?.employeeId||"");const [ratings,setRatings]=useState<Record<string,string>>({});const [knowledgeLevel,setKnowledgeLevel]=useState<Record<string,string>>({});const [text,setText]=useState({bestModule:"",missedModule:"",majorLearning:"",ideasToImplement:"",remarks:""});const [editing,setEditing]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 const load=async()=>{const requests:any[]=[api.get<Training[]>("/trainings"),api.get<FeedbackRow[]>("/feedback")];if(!employee)requests.push(api.get<Employee[]>("/employees"));const [t,f,e]=await Promise.all(requests);setTrainings(t.data||[]);setRows(f.data||[]);if(e)setEmployees(e.data||[]);if(!trainingId&&t.data?.[0])setTrainingId(t.data[0]._id)};useEffect(()=>{load().catch(()=>{})},[]);
 const existing=useMemo(()=>rows.find(r=>r.trainingId===trainingId&&r.employeeId===employeeId),[rows,trainingId,employeeId]);const selected=useMemo(()=>trainings.find(t=>t._id===trainingId),[trainings,trainingId]);
 useEffect(()=>{if(existing){const rr:Record<string,string>={};Object.entries(existing.ratings||{}).forEach(([k,v])=>rr[k]=labels[(Number(v)||1)-1]||"");setRatings(rr);setEditing(true)}else{setRatings({});setEditing(false)}},[existing]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(!trainingId||!employeeId)return setError("Select training and trainee.");if(ratingRows.some(x=>!ratings[x]))return setError("Please complete all course ratings.");try{const payload={trainingId,employeeId,programme:selected?.title,participantName:employees.find(x=>x.employeeId===employeeId)?.name||user?.name,location:selected?.venue||"",dates:selected?.startDate||selected?.trainingDate||"",trainer:selected?.trainerName||"",ratings:Object.fromEntries(Object.entries(ratings).map(([k,v])=>[k,score(v)])),knowledgeBefore:knowledgeLevel.before||"",knowledgeAfter:knowledgeLevel.after||"",...text};if(existing)await api.put("/feedback",payload);else await api.post("/feedback",payload);setMessage("Feedback submitted successfully.");await load()}catch(e:any){setError(e?.response?.data?.message||"Unable to save feedback.")}};
 return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-medium text-indigo-600">Training Feedback</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">{employee?"My Training Feedback":"Training Feedback"}</h1><p className="mt-2 text-sm text-slate-500">{employee?"Submit feedback after attending a training.":"HR Admin and Managers can also submit feedback for assigned trainees."}</p></div>{message&&<div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700"><CheckCircle2 size={18}/>{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
 {!employee&&<section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-semibold">Submitted feedback</h2></div><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead className="bg-slate-50"><tr>{["Employee","Department","Training","Overall","Status"].map(x=><th key={x} className="p-4 text-left">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={`${r.trainingId}-${r.employeeId}`} className="border-t"><td className="p-4">{r.employeeName||r.employeeId}</td><td className="p-4">{r.department||"—"}</td><td className="p-4">{r.trainingTitle||r.trainingId}</td><td className="p-4">{r.ratings?.overall||"—"} / 5</td><td className="p-4">{r.status||"Submitted"}</td></tr>)}</tbody></table></div></section>}
 <form onSubmit={submit} className="space-y-7 rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-medium">Training</label><select value={trainingId} onChange={e=>setTrainingId(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm"><option value="">Select assigned training</option>{trainings.map(t=><option key={t._id} value={t._id}>{t.title}</option>)}</select></div>{!employee&&<div><label className="mb-2 block text-sm font-medium">Trainee</label><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} className="w-full rounded-xl border px-4 py-3 text-sm"><option value="">Select trainee</option>{employees.map(e=><option key={e.employeeId} value={e.employeeId}>{e.employeeId} - {e.name} - {e.department}</option>)}</select></div>}<div><label className="mb-2 block text-sm font-medium">Trainer</label><input readOnly value={selected?.trainerName||""} className="w-full rounded-xl border bg-slate-50 px-4 py-3 text-sm"/></div><div><label className="mb-2 block text-sm font-medium">Training date</label><input readOnly value={selected?.startDate||selected?.trainingDate||""} className="w-full rounded-xl border bg-slate-50 px-4 py-3 text-sm"/></div></div>
 <section><h2 className="mb-3 font-semibold">Course rating</h2><div className="overflow-x-auto rounded-xl border"><table className="min-w-[720px] w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Aspect</th>{labels.map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{ratingRows.map(row=><tr key={row} className="border-t"><td className="p-3 font-medium">{row==="overall"?"Overall rating":row}</td>{labels.map(x=><td key={x} className="p-3 text-center"><input type="radio" name={row} checked={ratings[row]===x} onChange={()=>setRatings({...ratings,[row]:x})}/></td>)}</tr>)}</tbody></table></div></section>
 <section><h2 className="mb-3 font-semibold">Knowledge before / after programme</h2><div className="overflow-x-auto rounded-xl border"><table className="min-w-[720px] w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Level</th>{knowledge.map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{[["before","Before programme"],["after","After programme"]].map(([key,label])=><tr key={key} className="border-t"><td className="p-3 font-medium">{label}</td>{knowledge.map(x=><td key={x} className="p-3 text-center"><input type="radio" name={key} checked={knowledgeLevel[key]===x} onChange={()=>setKnowledgeLevel({...knowledgeLevel,[key]:x})}/></td>)}</tr>)}</tbody></table></div></section>
 <section className="grid gap-4">{[["bestModule","Which module you liked best"],["missedModule","Which module you think we missed"],["majorLearning","What was the major learning for you"],["ideasToImplement","Ideas you can implement"],["remarks","Any other remarks"]].map(([key,label])=><div key={key}><label className="mb-2 block text-sm font-medium">{label}</label><textarea value={text[key as keyof typeof text]} onChange={e=>setText({...text,[key]:e.target.value})} rows={key==="remarks"?4:3} className="w-full rounded-xl border px-4 py-3 text-sm"/></div>)}</section><div className="flex justify-end border-t pt-5"><button type="submit" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">{editing?<Edit3 size={17}/>:<Send size={17}/>} {editing?"Update Feedback":"Submit Feedback"}</button></div></form></div>
}