import { useEffect, useState } from "react";
import { BarChart3, Download, Eye, FileText, Users } from "lucide-react";
import { api } from "../services/api";

type Training={_id:string;title:string;startDate?:string;endDate?:string;trainerName?:string;status?:string};
type Report={title:string;columns:string[];rows:Record<string,any>[]};
async function download(path:string,filename:string){const r=await api.get(`${path}?format=csv`,{responseType:"blob"});const url=URL.createObjectURL(r.data);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
export default function Reports(){const [trainings,setTrainings]=useState<Training[]>([]);const [selected,setSelected]=useState<Training|null>(null);const [report,setReport]=useState<Report|null>(null);const [loading,setLoading]=useState(false);useEffect(()=>{api.get<Training[]>("/reports/trainings").then(r=>setTrainings(r.data||[])).catch(()=>{})},[]);
 const view=async(type:string)=>{if(!selected)return;setLoading(true);try{const r=await api.get<any>(`/reports/training/${selected._id}/${type}`);const rows=r.data?.rows||[];setReport({title:type==="attendance"?"Attendance Report":type==="feedback"?"Feedback Report":"Trainee / Trainer Report",columns:rows.length?Object.keys(rows[0]):[],rows})}catch(e:any){alert(e?.response?.data?.message||"Unable to load report")}finally{setLoading(false)}};
 return <div className="space-y-6"><div><p className="text-sm font-medium text-indigo-600">Reports</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Training Reports</h1><p className="mt-2 text-sm text-slate-500">Choose a training to view attendance, feedback and trainee/trainer reports.</p></div>{selected&&<section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-slate-500">Selected training</p><h2 className="text-lg font-bold">{selected.title}</h2><p className="text-sm text-slate-500">{selected.trainerName||"No trainer"} · {selected.startDate?new Date(selected.startDate).toLocaleString("en-IN"):"—"}</p></div><button onClick={()=>{setSelected(null);setReport(null)}} className="rounded-xl border px-4 py-2 text-sm font-semibold">Back to trainings</button></div><div className="mt-5 grid gap-3 md:grid-cols-3"><ReportButton icon={<BarChart3 size={20}/>} title="Attendance" onClick={()=>view("attendance")} download={()=>download(`/reports/training/${selected._id}/attendance`,"attendance-report.csv")}/><ReportButton icon={<FileText size={20}/>} title="Feedback" onClick={()=>view("feedback")} download={()=>download(`/reports/training/${selected._id}/feedback`,"feedback-report.csv")}/><ReportButton icon={<Users size={20}/>} title="Trainee / Trainer" onClick={()=>view("trainee-trainer")} download={()=>download(`/reports/training/${selected._id}/trainee-trainer`,"trainee-trainer-report.csv")}/></div></section>}
 {!selected&&<section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{trainings.map(t=><button key={t._id} onClick={()=>setSelected(t)} className="rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-300"><div className="flex items-center justify-between"><FileText size={21} className="text-indigo-600"/><Eye size={18} className="text-slate-400"/></div><h2 className="mt-4 font-bold">{t.title}</h2><p className="mt-1 text-sm text-slate-500">{t.trainerName||"No trainer"}</p><p className="mt-2 text-xs text-slate-400">{t.startDate?new Date(t.startDate).toLocaleString("en-IN"):"—"} → {t.endDate?new Date(t.endDate).toLocaleString("en-IN"):"—"}</p></button>)}{!trainings.length&&<p className="rounded-xl bg-white p-8 text-sm text-slate-500">No trainings available.</p>}</section>}
 {report&&<section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">{report.title}</h2><p className="text-sm text-slate-500">{report.rows.length} record(s)</p></div><button onClick={()=>setReport(null)} className="rounded-lg border px-3 py-2 text-sm">Close report</button></div><div className="overflow-x-auto">{loading?<p className="p-8">Loading...</p>:<table className="min-w-[800px] w-full text-sm"><thead className="bg-slate-50"><tr>{report.columns.map(c=><th key={c} className="p-3 text-left">{c}</th>)}</tr></thead><tbody>{report.rows.map((row,i)=><tr key={i} className="border-t">{report.columns.map(c=><td key={c} className="p-3">{String(row[c]??"—")}</td>)}</tr>)}</tbody></table>}</div></section>}</div>}
function ReportButton({icon,title,onClick,download}:{icon:any;title:string;onClick:()=>void;download:()=>void}){return <div className="rounded-xl border p-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-indigo-50 p-2 text-indigo-600">{icon}</div><b>{title} report</b></div><div className="mt-4 flex gap-2"><button onClick={onClick} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-semibold text-white"><Eye size={14}/>View</button><button onClick={download} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold"><Download size={14}/>Download</button></div></div>}
