import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { CalendarDays, CheckCircle2, Clock3, Plus, Search, UserPlus, Users, X } from "lucide-react";
import { api } from "../services/api";
import { useAuth } from "../auth/AuthContext";

type Training = { _id:string; title:string; content?:string; trainingType:string; trainerName:string; trainerCategory:string; venue:string; trainingDate:string; trainingMode:string; durationMinutes:number; status:string; departments:string[]; traineeIds:string[] };
type Employee = { employeeId:string; name:string; department:string; designation:string; status:string };
const types=["Technical","Behavioural","Leadership"]; const modes=["Company-wide","Customized","One-to-One","Refresher"];
const empty={title:"",content:"",trainingType:"Technical",trainerName:"",trainerCategory:"Internal",venue:"",departments:"Production",trainingDate:"",trainingMode:"Company-wide",durationHours:"1",durationMinutes:"0"};

export default function Trainings(){
 const {user}=useAuth(); const [items,setItems]=useState<Training[]>([]); const [employees,setEmployees]=useState<Employee[]>([]); const [search,setSearch]=useState(""); const [type,setType]=useState("All Types"); const [status,setStatus]=useState("All Status"); const [open,setOpen]=useState(false); const [assign,setAssign]=useState<Training|null>(null); const [selected,setSelected]=useState<string[]>([]); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 const load=()=>api.get<Training[]>("/trainings").then(r=>setItems(r.data)).catch(()=>setItems([]));
 useEffect(()=>{load(); api.get<Employee[]>("/employees").then(r=>setEmployees(r.data)).catch(()=>{});},[]);
 const filtered=useMemo(()=>items.filter(x=>(type==="All Types"||x.trainingType===type)&&(status==="All Status"||x.status===status)&&`${x.title} ${x.trainerName}`.toLowerCase().includes(search.toLowerCase())),[items,type,status,search]);
 const add=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await api.post("/trainings",{...form,departments:[form.departments],traineeIds:[],durationMinutes:Number(form.durationHours)*60+Number(form.durationMinutes)});setMessage("Training created successfully.");setOpen(false);setForm(empty);load();}catch(err:any){setMessage(err?.response?.data?.message||"Unable to create training.");}finally{setSaving(false);}};
 const openAssign=async(t:Training)=>{setAssign(t);setSelected(t.traineeIds||[]); if(!employees.length) await api.get<Employee[]>("/employees").then(r=>setEmployees(r.data)).catch(()=>{});};
 const saveAssign=async()=>{if(!assign)return;setSaving(true);try{await api.put(`/trainings/${assign._id}/participants`,{employeeIds:selected});setMessage(`${selected.length} participant(s) assigned.`);setAssign(null);load();}catch(err:any){setMessage(err?.response?.data?.message||"Unable to update participants.");}finally{setSaving(false);}};
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <div className="space-y-6">
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-indigo-600">HR / Admin</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Training Management</h1><p className="mt-2 text-sm text-slate-500">Create, schedule, assign and complete employee training programmes.</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white hover:bg-indigo-700"><Plus size={18}/> Add Training</button></div>
  {message&&<div className="flex items-center justify-between rounded-xl bg-emerald-50 p-4 text-sm font-medium text-emerald-700"><span className="flex items-center gap-2"><CheckCircle2 size={18}/>{message}</span><button onClick={()=>setMessage("")}><X size={17}/></button></div>}
  <div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_auto_auto]"><div className="relative"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search training or trainer..." className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-4 text-sm outline-none focus:border-indigo-500"/></div><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm"><option>All Types</option>{types.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm"><option>All Status</option><option>Scheduled</option><option>Completed</option><option>Cancelled</option></select></div>
  <div className="grid gap-4 lg:grid-cols-2">{filtered.map(t=><article key={t._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{t.trainingType}</span><h2 className="mt-3 text-lg font-bold">{t.title}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${t.status==="Completed"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{t.status}</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-500">{t.content||"No training description provided."}</p><div className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-2"><div className="flex gap-2"><CalendarDays size={17}/>{t.trainingDate||"Date not set"}</div><div className="flex gap-2"><Clock3 size={17}/>{Math.floor(t.durationMinutes/60)}h {t.durationMinutes%60}m</div><div className="flex gap-2"><Users size={17}/>{t.traineeIds?.length||0} participants</div><div>{t.trainerName||"Trainer not set"} · {t.trainerCategory}</div></div><div className="mt-5 flex flex-wrap gap-2">{(t.departments||[]).map(d=><span key={d} className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{d}</span>)}</div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><button onClick={()=>openAssign(t)} className="inline-flex items-center gap-1 rounded-lg bg-indigo-50 px-3 py-2 text-xs font-semibold text-indigo-700"><UserPlus size={14}/> Assign Employees</button><button onClick={()=>api.post(`/trainings/${t._id}/complete`).then(()=>{setMessage("Training marked complete.");load()})} disabled={t.status==="Completed"} className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold disabled:opacity-50"><CheckCircle2 size={14}/> {t.status==="Completed"?"Completed":"Mark Complete"}</button></div></article>)}</div>
  {open&&<Modal title="Add Training" onClose={()=>setOpen(false)}><form onSubmit={add} className="grid gap-4 sm:grid-cols-2">{[["Training title","title","text"],["Trainer name","trainerName","text"],["Venue","venue","text"],["Training date","trainingDate","date"]].map(([label,key,inputType])=><div key={key} className={key==="title"?"sm:col-span-2":""}><label className="mb-1.5 block text-sm font-medium">{label}</label><input required={key==="title"} type={inputType} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div>)}<Select label="Training type" value={form.trainingType} options={types} onChange={v=>setForm({...form,trainingType:v})}/><Select label="Trainer category" value={form.trainerCategory} options={["Internal","External"]} onChange={v=>setForm({...form,trainerCategory:v})}/><Select label="Training mode" value={form.trainingMode} options={modes} onChange={v=>setForm({...form,trainingMode:v})}/><Select label="Department" value={form.departments} options={["Production","QA / Quality","Store","HR","Maintenance","Engineering / R&D","Finance","Purchase","Sales","Management","Other"]} onChange={v=>setForm({...form,departments:v})}/><div className="sm:col-span-2"><label className="mb-1.5 block text-sm font-medium">Training content</label><textarea rows={3} value={form.content} onChange={e=>setForm({...form,content:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div><div><label className="mb-1.5 block text-sm font-medium">Hours</label><input type="number" min="0" value={form.durationHours} onChange={e=>setForm({...form,durationHours:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div><div><label className="mb-1.5 block text-sm font-medium">Minutes</label><input type="number" min="0" max="59" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></div><Actions onClose={()=>setOpen(false)} saving={saving}/></form></Modal>}
  {assign&&<Modal title={`Assign Employees · ${assign.title}`} onClose={()=>setAssign(null)}><div className="mb-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-800">Select employees who should appear on the attendance sheet and receive the feedback task.</div><div className="max-h-[55vh] space-y-2 overflow-y-auto">{employees.map(e=><label key={e.employeeId} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${selected.includes(e.employeeId)?"border-indigo-300 bg-indigo-50":"border-slate-200"}`}><input type="checkbox" checked={selected.includes(e.employeeId)} onChange={()=>toggle(e.employeeId)} className="h-4 w-4 accent-indigo-600"/><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{e.name} <span className="font-normal text-slate-500">({e.employeeId})</span></span><span className="block text-xs text-slate-500">{e.department} · {e.designation}</span></span></label>)}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-sm text-slate-500">{selected.length} selected</p><div className="flex gap-2"><button onClick={()=>setAssign(null)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={saveAssign} disabled={saving} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving...":"Save Assignment"}</button></div></div></Modal>}
 </div>
}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <div><label className="mb-1.5 block text-sm font-medium">{label}</label><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{options.map(x=><option key={x}>{x}</option>)}</select></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-7"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">{title}</h2></div><button onClick={onClose} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X size={19}/></button></div><div className="mt-6">{children}</div></div></div>}
function Actions({onClose,saving}:{onClose:()=>void;saving:boolean}){return <div className="sm:col-span-2 flex justify-end gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Creating...":"Create Training"}</button></div>}
